services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    build:
      context: ./adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  pgdata:
