services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  adminer:
    build:
      context: ./adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - internal

  backend:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
  node_modules:
