services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


  adminer:
    image: adminer:5.2.1
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgresql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: postgres
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  pgdata:
  adminer:
