"""include seed data endpoint

Revision ID: 77d4b3d2f220
Revises: 0de534d84701
Create Date: 2025-05-28 14:51:48.325127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d4b3d2f220'
down_revision: Union[str, None] = '0de534d84701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_seed_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_seed_data')
    # ### end Alembic commands ###
